# http://www.appveyor.com/docs/appveyor-yml
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    # node.js
    - nodejs_version: "stable"
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - if "%nodejs_version%"=="stable" (npm test) else (node_modules\.bin\mocha --async-only && npm run test-types)

build: off

# build version format
version: "{build}"
